server:
  port: 9004
spring:
  application:
    name: consumer-login
  main:
    allow-bean-definition-overriding: true

#eureka配置，注册到注册中心
eureka:
  client:
    service-url:
      defaultZone: http://www.eureka7001.com:7001/eureka/
    fetch-registry: true
    register-with-eureka: true
  instance:
    instance-id: ${spring.application.name}-${server.port}
